stages:
  - build
  - deploy


before_script:
  - . ~/profile.d/nvmrc.sh
#  - nvm use 18.18.2

build-bot:
  stage: build
  only:
    refs:
      - master
  before_script:
    - cp ${envbest} .env.best
    - cp ${envcake} .env.cake
  script:
   - ssh root@docker-pc.pir.lan "cd /opt/expocab-bot/; git pull"
   - rsync .env.best root@docker-pc.pir.lan:/opt/expocab-bot/.
   - rsync .env.cake root@docker-pc.pir.lan:/opt/expocab-bot/.
   - ssh root@docker-pc.pir.lan "cd /opt/expocab-bot/; docker-compose build"


deploy-bot:
  stage: deploy
  only:
    refs:
      - master
  script:
   - ssh root@docker-pc.pir.lan "source ~/.bashrc ||cd /opt/expocab-bot/ || docker-compose up -d --force-recreate"